package com.manufacturing.backend.common;

public enum EmployeePosition {
    PRODUCTION_TECHNICIAN,
    MECHANICAL_ENGINEER,
    LINE_LEAD,
    QUALITY_ASSURANCE_SPECIALIST,
    OPERATIONS_COORDINATOR,
    ASSEMBLY_OPERATOR,
    MAINTENANCE_TECHNICIAN,
    SUPPLY_CHAIN_COORDINATOR,
    EHS_OFFICER,
    SHIFT_MANAGER,
    PROCESS_ENGINEER
}
