version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: manufacturing_order_management_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: manufacturing_order_management_db
    ports:
      - '5433:5432'
    volumes:
      - manufacturing_order_management_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: .
    container_name: manufacturing_order_management_backend
    ports:
      - '8082:8082'
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: default
    restart: unless-stopped

volumes:
  manufacturing_order_management_data:
